### ISSUE TITLE
Move to diffux organization

### ISSUE THREAD

**Issue by lencioni** [trotzig/likadan#35]
I think that this project might benefit from being under the broader diffux umbrella, and it will make it easier for us to collaborate on it. I think that diffux-ci would be a good name for it as well.

**Comment by trotzig** [comment]
As we've discussed before, I agree. 

Here's a proposed sequence of events:
- Rename everything `likadan` to `diffux-ci`
- Move the project to the Diffux organization
- Publish version 1.0.0(?) of diffux-ci as a gem
- Publish a new version of the likadan gem that will print deprecation warnings

Apparently, there [doesn't seem to be a way to rename a gem](http://stackoverflow.com/questions/13440438/how-to-rename-a-gem). Instead, you push a new name and deprecate the old.

What do you think?

**Comment by trotzig** [comment]
Renaming is happening in this branch: https://github.com/trotzig/likadan/tree/rename-to-diffux-ci

**Comment by lencioni** [comment]
I think that sounds like a solid plan!
